Revert "Regenerate requirements for Python 3.7"
This reverts commit 9e79f23efdce18ff1ab92c45273f2bcdd463c3b7 which was made in
error: this project no longer supports Python 3.7.